# Generated by Django 4.2.19 on 2025-02-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='list',
            new_name='lists',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='task',
            new_name='tasks',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.list'),
        ),
    ]
