# Generated by Django 4.2.19 on 2025-02-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_list_tag_lists_rename_task_tag_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_number', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='todo.list')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.task'),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
