# Generated by Django 4.2.19 on 2025-02-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_alter_tag_tasks_delete_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_number',
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.list'),
        ),
    ]
